### PR TITLE
feat(ui): Filters for proposals

### PR DESCRIPTION
**Pull request by luisivan**

### CODE REVIEW

**Review by aahna-ashina — CHANGES_REQUESTED** [review]
@luisivan Build error:
```typescript
./pages/proposals/index.tsx:49:23
Type error: Type 'true' is not assignable to type 'string | number | readonly string[] | undefined'.
```

**Comment by luisivan** [comment]
@aahna-ashina fixed, it also had the same error previously present in https://github.com/nation3/gov-app/pull/6 so I merged both branches

**Review by aahna-ashina — CHANGES_REQUESTED** [review]
https://github.com/nation3/gov-app/actions/runs/3052233538/jobs/4921386237

**Comment by luisivan** [comment]
@aahna-ashina can we just kill the checks on Node 18? Vercel uses Node 16, so we don't really care

**Comment by aahna-ashina** [comment]
> @aahna-ashina can we just kill the checks on Node 18? Vercel uses Node 16, so we don't really care

@luisivan Yes, we can do that.  As long as it won't fail for developers who have Node 18 installed?

You can adjust this in `.github/workflows/yarn.yml`

**Comment by luisivan** [comment]
> @luisivan Yes, we can do that. As long as it won't fail for developers who have Node 18 installed?

We can just add a disclaimer that devs shouldn't run this on Node 18

**Pull request merged**
